/**
 * Cross-validation test: compare TypeScript multi-cpu simulator output
 * against the Python reference implementation (multi.py).
 *
 * The expected data was generated by test-multi-cpu-compare.py, which
 * re-implements the Python simulator logic and dumps structured JSON.
 */
import { describe, it, expect } from "vitest";
import { simulate, defaultOptions } from "./multi-cpu";
import type { SimulationOptions } from "./multi-cpu";
import expected from "../../../test-multi-cpu-expected.json";

interface PyTick {
  job: string | null;
  timeLeft: number;
  cacheState: string[];
}

interface PyResult {
  jobList: string;
  finishedTime: number;
  ticks: PyTick[][];
  stats: { utilization: number; warmUtilization: number }[];
}

const testCases: { label: string; opts: Partial<SimulationOptions> }[] = [
  { label: "default_seed0", opts: {} },
  { label: "seed1", opts: { seed: 1 } },
  { label: "seed2", opts: { seed: 2 } },
  { label: "seed42", opts: { seed: 42 } },
  { label: "3cpus_seed0", opts: { numCpus: 3 } },
  { label: "4cpus_seed1", opts: { seed: 1, numCpus: 4 } },
  {
    label: "explicit_jobs",
    opts: { jobList: "a:30:50,b:20:80,c:40:30" },
  },
  { label: "warmup0", opts: { cacheWarmupTime: 0 } },
  {
    label: "warmup5_rate3",
    opts: { cacheWarmupTime: 5, cacheRateWarm: 3 },
  },
  { label: "timeslice5", opts: { timeSlice: 5 } },
  { label: "per_cpu", opts: { perCpuQueues: true, seed: 0 } },
  {
    label: "per_cpu_3cpus",
    opts: { perCpuQueues: true, numCpus: 3, seed: 0 },
  },
  { label: "many_jobs", opts: { jobNum: 6, seed: 3 } },
  { label: "small_cache", opts: { cacheSize: 50, seed: 0 } },
];

describe("multi-cpu: TypeScript vs Python cross-validation", () => {
  for (const tc of testCases) {
    describe(tc.label, () => {
      const fullOpts: SimulationOptions = { ...defaultOptions, ...tc.opts };
      const result = simulate(fullOpts);
      const py = (expected as Record<string, PyResult>)[tc.label];

      it("finishedTime matches", () => {
        expect(result.finishedTime).toBe(py.finishedTime);
      });

      it("tick count matches", () => {
        expect(result.ticks.length).toBe(py.ticks.length);
      });

      it("every tick matches (job, timeLeft, cacheState)", () => {
        for (let t = 0; t < py.ticks.length; t++) {
          for (let cpu = 0; cpu < fullOpts.numCpus; cpu++) {
            const ts = result.ticks[t][cpu];
            const pyT = py.ticks[t][cpu];

            if (ts.job !== pyT.job) {
              expect.fail(
                `tick ${t} cpu ${cpu}: job mismatch: TS=${ts.job} PY=${pyT.job}`
              );
            }
            if (ts.timeLeft !== pyT.timeLeft) {
              expect.fail(
                `tick ${t} cpu ${cpu}: timeLeft mismatch: TS=${ts.timeLeft} PY=${pyT.timeLeft}`
              );
            }
            if (JSON.stringify(ts.cacheState) !== JSON.stringify(pyT.cacheState)) {
              expect.fail(
                `tick ${t} cpu ${cpu}: cacheState mismatch: TS=${JSON.stringify(ts.cacheState)} PY=${JSON.stringify(pyT.cacheState)}`
              );
            }
          }
        }
      });

      it("stats match", () => {
        for (let cpu = 0; cpu < fullOpts.numCpus; cpu++) {
          expect(result.stats[cpu].utilization).toBeCloseTo(
            py.stats[cpu].utilization,
            1
          );
          expect(result.stats[cpu].warmUtilization).toBeCloseTo(
            py.stats[cpu].warmUtilization,
            1
          );
        }
      });
    });
  }
});
