/**
 * Cross-validation tests: compare TypeScript RAID simulator output against
 * known-good Python simulator (raid.py) output for identical parameters.
 *
 * Each test case was generated by running the Python simulator with `-c` flag
 * and recording the exact logical addresses, read/write decisions, and
 * physical disk operations.
 */
import { describe, it, expect } from 'vitest';
import { simulate, type RaidParams, type PhysicalOp, defaultParams } from './raid';

interface ExpectedRequest {
  logicalAddr: number;
  size: number;
  isWrite: boolean;
  ops: PhysicalOp[];
}

function check(params: RaidParams, expected: ExpectedRequest[]) {
  const result = simulate(params);
  expect(result.requests.length).toBe(expected.length);
  for (let i = 0; i < expected.length; i++) {
    const got = result.requests[i];
    const exp = expected[i];
    expect(got.logicalAddr, `req ${i} logicalAddr`).toBe(exp.logicalAddr);
    expect(got.size, `req ${i} size`).toBe(exp.size);
    expect(got.isWrite, `req ${i} isWrite`).toBe(exp.isWrite);
    expect(got.ops, `req ${i} ops`).toEqual(exp.ops);
  }
}

describe('Python cross-validation', () => {
  // python3 raid.py -L 0 -D 4 -s 0 -n 5 -c
  it('RAID-0, 4 disks, seed=0, 5 random reads', () => {
    check(
      { ...defaultParams, level: 0, numDisks: 4, seed: 0, numRequests: 5 },
      [
        { logicalAddr: 8444, size: 1, isWrite: false, ops: [{ type: 'read', disk: 0, offset: 2111 }] },
        { logicalAddr: 4205, size: 1, isWrite: false, ops: [{ type: 'read', disk: 1, offset: 1051 }] },
        { logicalAddr: 5112, size: 1, isWrite: false, ops: [{ type: 'read', disk: 0, offset: 1278 }] },
        { logicalAddr: 7837, size: 1, isWrite: false, ops: [{ type: 'read', disk: 1, offset: 1959 }] },
        { logicalAddr: 4765, size: 1, isWrite: false, ops: [{ type: 'read', disk: 1, offset: 1191 }] },
      ],
    );
  });

  // python3 raid.py -L 1 -D 4 -s 12 -n 5 -w 50 -c
  it('RAID-1, 4 disks, seed=12, 50% writes', () => {
    check(
      { ...defaultParams, level: 1, numDisks: 4, seed: 12, numRequests: 5, writeFrac: 50 },
      [
        { logicalAddr: 4745, size: 1, isWrite: false, ops: [{ type: 'read', disk: 2, offset: 2372 }] },
        { logicalAddr: 6664, size: 1, isWrite: true, ops: [
          { type: 'write', disk: 0, offset: 3332 },
          { type: 'write', disk: 1, offset: 3332 },
        ]},
        { logicalAddr: 108, size: 1, isWrite: true, ops: [
          { type: 'write', disk: 0, offset: 54 },
          { type: 'write', disk: 1, offset: 54 },
        ]},
        { logicalAddr: 2740, size: 1, isWrite: false, ops: [{ type: 'read', disk: 0, offset: 1370 }] },
        { logicalAddr: 6905, size: 1, isWrite: false, ops: [{ type: 'read', disk: 2, offset: 3452 }] },
      ],
    );
  });

  // python3 raid.py -L 4 -D 5 -s 3 -n 5 -w 100 -c
  it('RAID-4, 5 disks, seed=3, all writes', () => {
    check(
      { ...defaultParams, level: 4, numDisks: 5, seed: 3, numRequests: 5, writeFrac: 100 },
      [
        { logicalAddr: 2379, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 3, offset: 594 }, { type: 'read', disk: 4, offset: 594 },
          { type: 'write', disk: 3, offset: 594 }, { type: 'write', disk: 4, offset: 594 },
        ]},
        { logicalAddr: 3699, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 3, offset: 924 }, { type: 'read', disk: 4, offset: 924 },
          { type: 'write', disk: 3, offset: 924 }, { type: 'write', disk: 4, offset: 924 },
        ]},
        { logicalAddr: 6257, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 1, offset: 1564 }, { type: 'read', disk: 4, offset: 1564 },
          { type: 'write', disk: 1, offset: 1564 }, { type: 'write', disk: 4, offset: 1564 },
        ]},
        { logicalAddr: 131, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 3, offset: 32 }, { type: 'read', disk: 4, offset: 32 },
          { type: 'write', disk: 3, offset: 32 }, { type: 'write', disk: 4, offset: 32 },
        ]},
        { logicalAddr: 2593, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 1, offset: 648 }, { type: 'read', disk: 4, offset: 648 },
          { type: 'write', disk: 1, offset: 648 }, { type: 'write', disk: 4, offset: 648 },
        ]},
      ],
    );
  });

  // python3 raid.py -L 5 -D 5 -s 7 -n 5 -w 50 -5 LS -c
  it('RAID-5 LS, 5 disks, seed=7, 50% writes', () => {
    check(
      { ...defaultParams, level: 5, numDisks: 5, seed: 7, numRequests: 5, writeFrac: 50, raid5type: 'LS' },
      [
        { logicalAddr: 3238, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 3, offset: 809 }, { type: 'read', disk: 0, offset: 809 },
          { type: 'write', disk: 3, offset: 809 }, { type: 'write', disk: 0, offset: 809 },
        ]},
        { logicalAddr: 6509, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 4, offset: 1627 }, { type: 'read', disk: 2, offset: 1627 },
          { type: 'write', disk: 4, offset: 1627 }, { type: 'write', disk: 2, offset: 1627 },
        ]},
        { logicalAddr: 5358, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 3, offset: 1339 }, { type: 'read', disk: 0, offset: 1339 },
          { type: 'write', disk: 3, offset: 1339 }, { type: 'write', disk: 0, offset: 1339 },
        ]},
        { logicalAddr: 579, size: 1, isWrite: false, ops: [{ type: 'read', disk: 4, offset: 144 }] },
        { logicalAddr: 374, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 4, offset: 93 }, { type: 'read', disk: 1, offset: 93 },
          { type: 'write', disk: 4, offset: 93 }, { type: 'write', disk: 1, offset: 93 },
        ]},
      ],
    );
  });

  // python3 raid.py -L 5 -D 5 -s 7 -n 5 -w 50 -5 LA -c
  it('RAID-5 LA, 5 disks, seed=7, 50% writes', () => {
    check(
      { ...defaultParams, level: 5, numDisks: 5, seed: 7, numRequests: 5, writeFrac: 50, raid5type: 'LA' },
      [
        { logicalAddr: 3238, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 3, offset: 809 }, { type: 'read', disk: 0, offset: 809 },
          { type: 'write', disk: 3, offset: 809 }, { type: 'write', disk: 0, offset: 809 },
        ]},
        { logicalAddr: 6509, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 1, offset: 1627 }, { type: 'read', disk: 2, offset: 1627 },
          { type: 'write', disk: 1, offset: 1627 }, { type: 'write', disk: 2, offset: 1627 },
        ]},
        { logicalAddr: 5358, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 3, offset: 1339 }, { type: 'read', disk: 0, offset: 1339 },
          { type: 'write', disk: 3, offset: 1339 }, { type: 'write', disk: 0, offset: 1339 },
        ]},
        { logicalAddr: 579, size: 1, isWrite: false, ops: [{ type: 'read', disk: 4, offset: 144 }] },
        { logicalAddr: 374, size: 1, isWrite: true, ops: [
          { type: 'read', disk: 3, offset: 93 }, { type: 'read', disk: 1, offset: 93 },
          { type: 'write', disk: 3, offset: 93 }, { type: 'write', disk: 1, offset: 93 },
        ]},
      ],
    );
  });

  // python3 raid.py -L 0 -D 4 -s 5 -n 5 -W seq -S 8k -c
  it('RAID-0, 4 disks, seed=5, sequential, reqSize=2 (8k)', () => {
    check(
      { ...defaultParams, level: 0, numDisks: 4, seed: 5, numRequests: 5, workload: 'seq', reqSize: 2 },
      [
        { logicalAddr: 0, size: 2, isWrite: false, ops: [
          { type: 'read', disk: 0, offset: 0 }, { type: 'read', disk: 1, offset: 0 },
        ]},
        { logicalAddr: 2, size: 2, isWrite: false, ops: [
          { type: 'read', disk: 2, offset: 0 }, { type: 'read', disk: 3, offset: 0 },
        ]},
        { logicalAddr: 4, size: 2, isWrite: false, ops: [
          { type: 'read', disk: 0, offset: 1 }, { type: 'read', disk: 1, offset: 1 },
        ]},
        { logicalAddr: 6, size: 2, isWrite: false, ops: [
          { type: 'read', disk: 2, offset: 1 }, { type: 'read', disk: 3, offset: 1 },
        ]},
        { logicalAddr: 8, size: 2, isWrite: false, ops: [
          { type: 'read', disk: 0, offset: 2 }, { type: 'read', disk: 1, offset: 2 },
        ]},
      ],
    );
  });
});
